version: "3.9"

services:
  skc-suggestion-engine:
    image: golang:1.19.5-bullseye
    command: go run .
    working_dir: /app
    ports:
      - "9001:9000"
    volumes:
      - "./:/app"
    restart: always
    deploy:
      resources:
        limits:
          memory: 200m
    networks:
      - skc-network
    environment:
      - SKC_SUGGESTION_ENGINE_DOT_ENV_FILE=.env_docker_local

networks:
  skc-network:
    name: skc-network
    driver: bridge