services:
  skc-suggestion-engine:
    image: alpine:latest
    command: ./skc-suggestion-engine
    working_dir: /app
    ports:
      - "9001:9000"
    volumes:
      - "./skc-suggestion-engine:/app/skc-suggestion-engine"
      - "./data/:/app/data/"
      - "./certs/:/app/certs/"
      - "./.env_docker_local:/app/.env_docker_local"
      - "/usr/share/zoneinfo/:/usr/share/zoneinfo/"
    restart: always
    deploy:
      resources:
        limits:
          memory: 75m
    networks:
      - skc
    environment:
      - SKC_SUGGESTION_ENGINE_DOT_ENV_FILE=.env_docker_local

networks:
  skc:
    name: skc
    driver: bridge
    external: true # network was alredy created, if you need to recreate the network - make this false
