services:
  skc-suggestion-engine:
    image: alpine:latest
    command: ./skc-suggestion-engine
    working_dir: /app
    ports:
      - "9000:9000"
    volumes:
      - "./skc-suggestion-engine:/app/skc-suggestion-engine"
      - "./data/:/app/data/"
      - "./certs/:/app/certs/"
      - "./.env_prod:/app/.env_prod"
      - "/usr/share/zoneinfo/:/usr/share/zoneinfo/"
    restart: always
    deploy:
      resources:
        limits:
          memory: 75m
    networks:
      - skc
    environment:
      - SKC_SUGGESTION_ENGINE_DOT_ENV_FILE=.env_prod
    labels:
      com.datadoghq.ad.init_configs: "[{}]"
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port": "%%port%%"}]'
      com.datadoghq.ad.logs: >-
        [{
          "source": "go",
          "service": "skc-suggestion-engine",
          "log_processing_rules": [{
            "type": "exclude_at_match",
            "name": "exclude_health_check",
            "pattern" : "\"app.flow\":\"Status\""
          }]
        }]
      com.datadoghq.tags.env: "prod"
      com.datadoghq.tags.service: "skc-suggestion-engine"

networks:
  skc:
    name: skc
    driver: bridge
    external: true # network was alredy created, if you need to recreate the network - make this false
